echo '---------------------------'
echo '---------------------------'
echo '_______HELLO,USER!_________'
echo 'FPRESSER IS' 
echo '       FREE TOOL FOR OSINT!' 
echo '---------------------------'
echo '____|good luck to you|_____'
echo '---------------------------'
echo '---------------------------'
